server:
  port: 8004

spring:
  application:
    name: microservicecloud-redis

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:
        instance-id: redisServer
        prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: microservicecloud
  company.name: www.mrzheng.com.cn
  build.artifactId: $project.artifactId$
  build.version:  $project.version$

